import { ArenaItem, BadgeItem } from '../types';

export const ARENAS_DATA: ArenaItem[] = [
  {
    id: 'agent_academy',
    tag: 'INTELLIGENT AGENTS',
    title: 'Agent Academy',
    subtitle: 'Goal-Based Intelligent Agent',
    difficulty: 'EASY',
    level: 'LV 1/10',
    mapLevelId: 1,
    colorGradient: 'from-blue-600 via-blue-700 to-indigo-800',
    iconSymbol: '▲',
    description: 'Step into the Academy and align sensor registers to escape using reflex goal predicates.',
  },
  {
    id: 'search_maze',
    tag: 'UNINFORMED SEARCH',
    title: 'Search Maze',
    subtitle: 'Breadth First Search (BFS)',
    difficulty: 'MEDIUM',
    level: 'LV 1/10',
    mapLevelId: 2,
    colorGradient: 'from-cyan-600 via-teal-600 to-emerald-700',
    iconSymbol: '✛',
    description: 'Navigate the graph labyrinth, expand the FIFO queue frontier, and find the shortest path to the exit.',
  },
  {
    id: 'heuristic_chamber',
    tag: 'INFORMED SEARCH',
    title: 'Heuristic Chamber',
    subtitle: 'A* Search',
    difficulty: 'MEDIUM',
    level: 'LV 1/10',
    mapLevelId: 3,
    colorGradient: 'from-red-600 via-orange-600 to-amber-600',
    iconSymbol: '▲',
    description: 'Calculate f(n) = g(n) + h(n), evaluate admissible Manhattan distance heuristics, and unlock the optimal path.',
  },
  {
    id: 'constraint_vault',
    tag: 'CONSTRAINT SATISFACTION PROBLEMS',
    title: 'Constraint Vault',
    subtitle: 'Backtracking Search (CSP)',
    difficulty: 'HARD',
    level: 'LV 1/10',
    mapLevelId: 4,
    colorGradient: 'from-emerald-500 via-green-600 to-teal-800',
    iconSymbol: '☒',
    description: 'Assign variables without domain violations using backtracking inference and arc consistency (AC-3).',
  },
  {
    id: 'strategy_arena',
    tag: 'ADVERSARIAL SEARCH',
    title: 'Strategy Arena',
    subtitle: 'Minimax and Alpha-Beta Pruning',
    difficulty: 'HARD',
    level: 'LV 1/10',
    mapLevelId: 5,
    colorGradient: 'from-amber-500 via-orange-600 to-rose-700',
    iconSymbol: '⬡',
    description: 'Prune suboptimal game tree branches with alpha-beta cutoffs and compute adversarial payoff matrices.',
  },
  {
    id: 'logic_archives',
    tag: 'KNOWLEDGE-BASED SYSTEMS',
    title: 'Logic Archives',
    subtitle: 'Forward and Backward Chaining',
    difficulty: 'MEDIUM',
    level: 'LV 1/10',
    mapLevelId: 6,
    colorGradient: 'from-emerald-400 via-teal-500 to-cyan-600',
    iconSymbol: '⚯',
    description: 'Deduce hidden facts and validate inference rules with Horn clause forward and backward chaining resolution.',
  },
  {
    id: 'core_ai_facility',
    tag: 'CLASSICAL LOGIC',
    title: 'Core AI Facility',
    subtitle: 'Propositional Logic, First Order Logic, and ...',
    difficulty: 'HARD',
    level: 'LV 1/10',
    mapLevelId: 7,
    colorGradient: 'from-slate-800 via-indigo-950 to-slate-900',
    iconSymbol: '◆',
    description: 'Execute propositional truth-table proofs, resolve First-Order quantifiers (∀, ∃), and stabilize the Core AI reactor.',
  },
];

export const BADGES_DATA: BadgeItem[] = [
  {
    id: 'first_escape',
    name: 'First Escape',
    description: 'Unlock level 1 of any arena',
    icon: '🏆',
    unlocked: false,
  },
  {
    id: 'academy_grad',
    name: 'Academy Graduate',
    description: 'Unlock level 10 of Agent Academy',
    icon: '🤖',
    unlocked: false,
  },
  {
    id: 'maze_runner',
    name: 'Maze Runner',
    description: 'Unlock level 10 of Search Maze',
    icon: '🧭',
    unlocked: false,
  },
  {
    id: 'informed_path',
    name: 'Informed Path',
    description: 'Unlock level 10 of Heuristic Chamber',
    icon: '🗺️',
    unlocked: false,
  },
  {
    id: 'constraint_breaker',
    name: 'Constraint Breaker',
    description: 'Unlock level 10 of Constraint Vault',
    icon: '🔓',
    unlocked: false,
  },
  {
    id: 'grandmaster_def',
    name: 'Grandmaster Def',
    description: 'Unlock level 10 of Strategy Arena',
    icon: '⚔️',
    unlocked: false,
  },
  {
    id: 'logic_archivist',
    name: 'Logic Master',
    description: 'Unlock level 10 of Logic Archives',
    icon: '📜',
    unlocked: false,
  },
  {
    id: 'classical_theorist',
    name: 'Core AI Theorist',
    description: 'Unlock level 10 of Core AI Facility',
    icon: '⚡',
    unlocked: false,
  },
];
